steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/[IMAGE]:[TAG]', '.' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push' ,'gcr.io/$PROJECT_ID/[IMAGE]:[TAG]' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', '[CLUSTER_NAME]', '--zone', 'asia-northeast1-b', '--project', '$PROJECT_ID' ]
  id: gcloud container clusters get-credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'k8s.yaml' ]
  id: kubectl apply
