apiVersion: apps/v1
kind: Deployment
metadata:
 name: [NAME]
spec:
 selector:
   matchLabels:
     app: [NAME]
 replicas: 1
 template:
   metadata:
     labels:
       app: [NAME]
   spec:
     containers:
     - name: [NAME]
       image: gcr.io/ca-tkg-test/[IMAGE_NAME]:[TAG]
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
       ports:
       - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
 name: [NAME]
spec:
 type: LoadBalancer
 selector:
   app: [NAME]
 ports:
 - name: http
   port: 8080
   targetPort: 8080
